### PR TITLE
Windows support

### PR DESCRIPTION
**Pull request by gdavison**
I've updated the Windows support and added some tests for the `default` case

### CODE REVIEW

**Comment by TD-4242** [comment]
This is awesome.  I will pull it down and test it out over the weekend.  Thanks for the update.

**Comment by TD-4242** [comment]
Is there an option I need to insure winrm is working?  it gets to the chocolaty cookbook then gives me an winrm auth error.

```
       ...
       Recipe: chocolatey::default
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #converge action: [WinRM::WinRMAuthorizationError]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

**Comment by gdavison** [comment]
Weird. I didn't have to change any settings from what's in the kitchen.yml file. Though it's not my VM, so it could have been changed.

What version of kitchen are you using? It needs at least v1.4. Are you using the VM from the download URL?

**Comment by TD-4242** [comment]
interesting, I'm on v1.4 that's include with chefdk 0.6.2.  It's strange that it seems to work at first then dies after already running several cookbook resources.  I'll poke at it a little today, then validate that nothing else seems broken and merge.

**Comment by TD-4242** [comment]
I finally setup a chefdk environment on a windows host and was able to fully converge and test.  I guess something doesn't work if testing from a linux (ubuntu 14.04) host.

**Comment by gdavison** [comment]
Interesting. I was running it from Mac OS. I would get occasional hangs, very rarely for Linux guests, but Windows seemed a bit more flakey.

**Pull request merged**
